# Generated by Django 4.2.5 on 2023-09-18 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_followrelationship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrelationship',
            name='followed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followrelationship',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='relationships',
            field=models.ManyToManyField(related_name='followed_by', through='api.FollowRelationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
