# Generated by Django 4.2.5 on 2023-09-18 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_followrelationship_followed_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="relationships",
            new_name="followed_users",
        ),
    ]
