# Generated by Django 4.2.5 on 2023-09-21 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_relationships_user_followed_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="imageURL",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="background_color",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="followrelationship",
            name="followed_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationship_as_followed_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="followrelationship",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationship_as_follower",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="followrelationship",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Active"), (0, "Blocked")], default=1
            ),
        ),
        migrations.CreateModel(
            name="CardStyleDeclaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="styles",
                        to="api.card",
                    ),
                ),
            ],
        ),
    ]
