# Generated by Django 4.2.5 on 2023-09-21 18:48

from django.db import migrations


def create_styles_for_existing_cards(apps, schema_editor):
    """
    Ensure that all existing cards have associated CardStyleDeclaration for background_color and font, if they have those properties.
    """
    Card = apps.get_model("api", "Card")
    for card in Card.objects.all():
        if card.background_color:
            card.styles.create(property="backgroundColor", value=card.background_color)
        if card.font:
            card.styles.create(property="font", value=card.font)
        card.save()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_card_imageurl_alter_card_background_color_and_more"),
    ]

    operations = [
        migrations.RunPython(create_styles_for_existing_cards),
    ]
