# Generated by Django 5.0a1 on 2023-09-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_auto_20230921_1848"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cardstyledeclaration",
            constraint=models.UniqueConstraint(
                fields=("property", "card"), name="no duplicate properties per card"
            ),
        ),
    ]
