# Generated by Django 5.0a1 on 2023-09-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_cardstyledeclaration_no_duplicate_properties_per_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardstyledeclaration",
            name="boolValue",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cardstyledeclaration",
            name="value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="cardstyledeclaration",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("value__isnull", False), ("boolValue__isnull", True)),
                    models.Q(("boolValue__isnull", False), ("value__isnull", True)),
                    _connector="OR",
                ),
                name="one_of_two_fields_null_constraint",
            ),
        ),
    ]
