# Generated by Django 5.0a1 on 2023-12-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_cardstyledeclaration_boolvalue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="font_size",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="text_align",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
